[2024-10-31T13:01:06.855+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_queimadas.check_emr_cluster_state manual__2024-10-31T13:00:59.480085+00:00 [queued]>
[2024-10-31T13:01:06.862+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_queimadas.check_emr_cluster_state manual__2024-10-31T13:00:59.480085+00:00 [queued]>
[2024-10-31T13:01:06.863+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-10-31T13:01:06.873+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): check_emr_cluster_state> on 2024-10-31 13:00:59.480085+00:00
[2024-10-31T13:01:06.880+0000] {standard_task_runner.py:60} INFO - Started process 8381 to run task
[2024-10-31T13:01:06.882+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_queimadas', 'check_emr_cluster_state', 'manual__2024-10-31T13:00:59.480085+00:00', '--job-id', '250', '--raw', '--subdir', 'DAGS_FOLDER/dag_cria_emr.py', '--cfg-path', '/tmp/tmp0yi80xi3']
[2024-10-31T13:01:06.884+0000] {standard_task_runner.py:88} INFO - Job 250: Subtask check_emr_cluster_state
[2024-10-31T13:01:06.914+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_queimadas.check_emr_cluster_state manual__2024-10-31T13:00:59.480085+00:00 [running]> on host 3f04bb9d0c09
[2024-10-31T13:01:06.963+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_queimadas' AIRFLOW_CTX_TASK_ID='check_emr_cluster_state' AIRFLOW_CTX_EXECUTION_DATE='2024-10-31T13:00:59.480085+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-31T13:00:59.480085+00:00'
[2024-10-31T13:01:07.634+0000] {logging_mixin.py:188} INFO - Cluster ainda está iniciando... Estado: STARTING
[2024-10-31T13:01:18.135+0000] {logging_mixin.py:188} INFO - Cluster ainda está iniciando... Estado: STARTING
[2024-10-31T13:01:28.720+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_cria_emr.py", line 189, in _check_emr_cluster_state
    raise Exception(f'Erro! Estado do cluster: {state}')
Exception: Erro! Estado do cluster: TERMINATING
[2024-10-31T13:01:28.727+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=etl_queimadas, task_id=check_emr_cluster_state, execution_date=20241031T130059, start_date=20241031T130106, end_date=20241031T130128
[2024-10-31T13:01:28.744+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 250 for task check_emr_cluster_state (Erro! Estado do cluster: TERMINATING; 8381)
[2024-10-31T13:01:28.767+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-31T13:01:28.778+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
