[2024-10-30T00:18:37.014+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_queimadas.check_emr_cluster_state manual__2024-10-30T00:18:26.629780+00:00 [queued]>
[2024-10-30T00:18:37.022+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_queimadas.check_emr_cluster_state manual__2024-10-30T00:18:26.629780+00:00 [queued]>
[2024-10-30T00:18:37.022+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-10-30T00:18:37.034+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): check_emr_cluster_state> on 2024-10-30 00:18:26.629780+00:00
[2024-10-30T00:18:37.041+0000] {standard_task_runner.py:60} INFO - Started process 728 to run task
[2024-10-30T00:18:37.043+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_queimadas', 'check_emr_cluster_state', 'manual__2024-10-30T00:18:26.629780+00:00', '--job-id', '209', '--raw', '--subdir', 'DAGS_FOLDER/dag_cria_emr.py', '--cfg-path', '/tmp/tmp1ow742dd']
[2024-10-30T00:18:37.045+0000] {standard_task_runner.py:88} INFO - Job 209: Subtask check_emr_cluster_state
[2024-10-30T00:18:37.095+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_queimadas.check_emr_cluster_state manual__2024-10-30T00:18:26.629780+00:00 [running]> on host 3f04bb9d0c09
[2024-10-30T00:18:37.352+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_queimadas' AIRFLOW_CTX_TASK_ID='check_emr_cluster_state' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T00:18:26.629780+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-30T00:18:26.629780+00:00'
[2024-10-30T00:18:38.168+0000] {logging_mixin.py:188} INFO - Cluster ainda está iniciando... Estado: STARTING
[2024-10-30T00:18:48.710+0000] {logging_mixin.py:188} INFO - Cluster ainda está iniciando... Estado: STARTING
[2024-10-30T00:18:59.296+0000] {logging_mixin.py:188} INFO - Cluster ainda está iniciando... Estado: STARTING
[2024-10-30T00:19:10.041+0000] {logging_mixin.py:188} INFO - Cluster ainda está iniciando... Estado: STARTING
[2024-10-30T00:19:20.611+0000] {logging_mixin.py:188} INFO - Cluster ainda está iniciando... Estado: STARTING
[2024-10-30T00:19:31.563+0000] {logging_mixin.py:188} INFO - Cluster ainda está iniciando... Estado: STARTING
[2024-10-30T00:19:42.418+0000] {logging_mixin.py:188} INFO - Cluster ainda está iniciando... Estado: STARTING
[2024-10-30T00:19:53.159+0000] {logging_mixin.py:188} INFO - Cluster ainda está iniciando... Estado: STARTING
[2024-10-30T00:20:04.098+0000] {logging_mixin.py:188} INFO - Cluster ainda está iniciando... Estado: STARTING
[2024-10-30T00:20:14.621+0000] {logging_mixin.py:188} INFO - Cluster ainda está iniciando... Estado: STARTING
[2024-10-30T00:20:25.140+0000] {logging_mixin.py:188} INFO - Cluster ainda está iniciando... Estado: STARTING
[2024-10-30T00:20:35.875+0000] {logging_mixin.py:188} INFO - Cluster ainda está iniciando... Estado: STARTING
[2024-10-30T00:20:46.443+0000] {logging_mixin.py:188} INFO - Cluster ainda está iniciando... Estado: STARTING
[2024-10-30T00:20:57.049+0000] {logging_mixin.py:188} INFO - Cluster ainda está iniciando... Estado: BOOTSTRAPPING
[2024-10-30T00:21:07.644+0000] {logging_mixin.py:188} INFO - Cluster ainda está iniciando... Estado: BOOTSTRAPPING
[2024-10-30T00:21:18.151+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_cria_emr.py", line 156, in _check_emr_cluster_state
    raise Exception(f'Erro! Estado do cluster: {state}')
Exception: Erro! Estado do cluster: TERMINATING
[2024-10-30T00:21:18.157+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=etl_queimadas, task_id=check_emr_cluster_state, execution_date=20241030T001826, start_date=20241030T001837, end_date=20241030T002118
[2024-10-30T00:21:18.171+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 209 for task check_emr_cluster_state (Erro! Estado do cluster: TERMINATING; 728)
[2024-10-30T00:21:18.182+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-30T00:21:18.199+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
